

title: "My Academic Website"
description: "A simple academic website on GitHub Pages"
theme: jekyll-theme-cayman

# Optional: configure your site's navigation
# Some themes support a "navbar" or "header_pages" setting
header_pages:
  - about.md
  - CV.md
  - Research.md
  - Teaching.md
